@extends('layouts.backend')
@section('title','Topup3')

@section('css')

@endsection

@section('content')
<div class="card">
	<div class="card-header">
		<div class="row">
			<div class="col-sm-6">
				<h5> Balance Sheet</h5>
			</div>
			<div class="col-sm-6">
				<button class="btn btn-primary btn-sm pull-right newTopup"> <i class="fa fa-plus"></i> New Topup</button>
			</div>
		</div>
	</div>
	<div class="card-block">
		<div class="dt-responsive table-responsive">
			<table id="TopupTable" class="table table-striped table-bordered nowrap text-center"></table>
		</div>
	</div>
</div>

<div class="modal fade" id="TopupModal" tabindex="-1" role="dialog">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<form id="TopupForm" method="post" action="{{route('topup.submit')}}" novalidate>
	        	<input type="hidden" name="brand_id" id="brand_id" class="brand_id">
	            <div class="modal-header">
	                <h4 class="modal-title">Add New Brand</h4>
	                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
	                    <span aria-hidden="true">&times;</span>
					</button>
				</div>
	            <div class="modal-body">
	                
                    <div class="form-group row">
                        <label class="col-sm-3 col-form-label">Topup Amount</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control form-control-sm" name="topup_amount" id="topup_amount" placeholder="Topup Amount">
                            <span class="messages"></span>
						</div>
					</div>
                    <div class="form-group row">
                        <label class="col-sm-3 col-form-label">Username</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control form-control-sm" name="username" id="username" placeholder="Username">
                            <span class="messages"></span>
						</div>
					</div>
                    <div class="form-group row">
                        <label class="col-sm-3 col-form-label">Topup Details</label>
                        <div class="col-sm-9">
                            <textarea class="form-control form-control-sm" name="topup_details" id="topup_details" placeholder="Topup Details"></textarea>
                            <span class="messages"></span>
						</div>
					</div>
                    <div class="form-group row">
                        <label class="col-sm-3 col-form-label">Status</label>
                        <div class="col-sm-9">
                        	<select class="form-control form-control-sm" name="topup_status" id="topup_status">
                        		<option value="">Select Status</option>
                        		<option value="Active">Active</option>
                        		<option value="Inactive">Inactive</option>
							</select>
                            <span class="messages"></span>
						</div>
					</div>
				</div>
	            <div class="modal-footer">
	                <button type="button" class="btn btn-sm btn-default waves-effect " data-dismiss="modal">Close</button>
	                <button type="submit" class="btn btn-sm btn-primary waves-effect waves-light" id="addBrand">Save</button>
				</div>
			</form>
		</div>
	</div>
</div>

@endsection

@section('js')

<script type="text/javascript">
	$(document).ready(function() {
		$('#TopupTable').DataTable({
			processing: true,
			serverSide: true,
			ajax: '{{route('topup.data') }}',
			columns: [
			{ title:'user_id', data: 'user_id'},
			{ title:'Topup Amount', data: 'topup_amount'},
			{ title:'Topup Details', data: 'topup_details'},
			{ title:'Generated By', data: 'topup_generate_by'},
			{ title:'Created Date', data: 'created_at'},
			{ title:'Topup Status', data: 'topup_status'},
			]
		});
		
		$('#TopupForm').ajaxForm({
			error: formError,
			success: function (responseText, statusText, xhr, $form) {
				formSuccess(responseText, statusText, xhr, $form);
				$('#TopupTable').DataTable().draw(true);
			},
			resetForm:true
		});
		
		$(document).on("click",'.newTopup',function(){
			$("#TopupModal").modal('toggle');
		});
	});
	
	
	
</script>

@endsection