@extends('layouts.backend')
@section('title','Balance Sheet')

@section('css')

@endsection

@section('content')
<div class="card">
	<div class="card-header">
		<button class="btn btn-primary btn-sm pull-right newTopup"> <i class="fa fa-plus"></i> New Topup</button>
	</div>
	<div class="card-body">
		<div class="dt-responsive table-responsive">
			<table id="TopupTable" class="table table-striped table-bordered nowrap text-center"></table>
		</div>
	</div>
</div>

<div class="modal fade" id="TopupModal" tabindex="-1" role="dialog">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<form id="TopupForm" method="post" action="{{route('admin.superadmin.topup.store')}}" novalidate>
	            <div class="modal-header">
	                <h4 class="modal-title">Add Topup</h4>
	                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
	                    <span aria-hidden="true">&times;</span>
					</button>
				</div>
	            <div class="modal-body">
                    <div class="form-group row">
                        <label class="col-sm-3 col-form-label">Topup Amount</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control form-control-sm" name="topup_amount" id="topup_amount" placeholder="Topup Amount">
                            <span class="messages"></span>
						</div>
					</div>
                    <div class="form-group row">
                        <label class="col-sm-3 col-form-label">Username</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control form-control-sm" name="username" id="username" placeholder="Username">
							<span class="messages username_check_status"></span>
						</div>
					</div>
				</div>
	            <div class="modal-footer">
	                <button type="button" class="btn btn-sm btn-default waves-effect " data-dismiss="modal">Close</button>
	                <button type="submit" class="btn btn-sm btn-primary waves-effect waves-light" id="addBrand">Save</button>
				</div>
			</form>
		</div>
	</div>
</div>
@endsection

@section('js')

<script type="text/javascript">
	$(document).ready(function() {
		$('#TopupTable').DataTable({
			processing: true,
			serverSide: true,
			ajax: '{{route("admin.superadmin.topup.data")}}',
			columns: [
			{ title:'ID', data: 'id'},
			{ title:'Username', data: 'name'},
			{ title:'Topup Amount', data: 'topup_amount'},
			{ title:'Topup Details', data: 'topup_details'},
			{ title:'Generated By', data: 'generate_by'},
			{ title:'Created Date', data: 'created_at'},
			{ title:'Topup From', data: 'from_user'},
			]
		});
		
		$('#TopupForm').ajaxForm({
			error: formError,
			success: function (responseText, statusText, xhr, $form) {
				formSuccess(responseText, statusText, xhr, $form);
				$('.username_check_status').html('');
				$('#TopupTable').DataTable().draw(true);
			},
			resetForm:true
		});
		
		$(document).on("click",'.newTopup',function(){
			$("#TopupModal").modal('toggle');
		});
		
		$(document).on("change",'input[name="username"]',function(){
			usernameCheck($(this),'.username_check_status');
		});
	});
	
	
	
</script>

@endsection